apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: worker
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: worker
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: worker
    spec:
      containers:
      - args:
        - node
        - worker/dist/server
        env:
        - name: APP_SECRET
        - name: DOMAIN_NAME
        - name: SMTP_HOST
        - name: SMTP_PASS
        - name: SMTP_PORT
        - name: SMTP_SECURED
        - name: SMTP_USER
        image: elcsrijan/learninglocker-ui:0.0.1
        imagePullPolicy: ""
        name: worker
        resources: {}
        volumeMounts:
        - mountPath: /opt/learninglocker/storage
          name: worker-claim0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: worker-claim0
        persistentVolumeClaim:
          claimName: worker-claim0
status: {}
