apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: xapi
  name: xapi
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: xapi
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: xapi
    spec:
      containers:
      - env:
        - name: MONGO_DB
          value: learninglocker_v2
        - name: MONGO_URL
          value: mongodb://mongo:27017/learninglocker_v2
        - name: REDIS_URL
          value: redis://redis:6379/0
        image: elcsrijan/learninglocker-xapi:0.0.1
        imagePullPolicy: ""
        name: xapi
        resources: {}
        volumeMounts:
        - mountPath: /usr/src/app/storage
          name: xapi-claim0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: xapi-claim0
        persistentVolumeClaim:
          claimName: xapi-claim0
status: {}
